### ISSUE TITLE
Missing Jalson files

### ISSUE THREAD

**Issue by kokonstas** [darrenjs/wampcc#10]
I'm trying to install following the instructions in the README, but I run into a few errors
The first is:

`autoreconf: configure.ac: subdirectory jalson not present
`
There is no jalson subdirectory on my system that I can find
After running autoconfig, trying to run:
`make install`
gives:
`vendor_jansson.h:10:66: fatal error: jansson.h: No such file or directory
`
Looking for any advice

**Comment by darrenjs** [comment]
Hi,  I think there was an error in the configure.ac  ... it was making a reference to jalson subdirectory.  That directory was removed a while back, but oddly the leftover reference didn't cause any error on my system when I ran autoreconf.    I've updated the configure.ac file on the master branch.  Hopefully fixes your issue.
