### ISSUE TITLE
build on windows fails due to missing openssl dependency

### ISSUE THREAD

**Issue by evanorsouw** [darrenjs/wampcc#14]
I am trying to build wampcc for Windows, but run into issues with openssl. Where cmake provides ways to specify the libuv and jansson dependencies there is no such thing for openssl. I can always hack it in, but I am wondering if there is a more formal way to do it.

**Comment by darrenjs** [comment]
Hi ... yeah you're right, looks like dependency check is missing for openssl, and is assumed to just be in standard locations (which it is on my computer).    I think option for openssl can be added  in just the same way as for jansson and libuv ... I'll try that out.  Thanks for flagging issue.

**Comment by samangh** [comment]
@darrenjs: we can probably close this, as the OpenSSL location can now be set using `-DOPENSSL_ROOT_DIR`

This was fixed in# 98057d8495bcc930bbda235866c9082c8dbd4d2c.
