### ISSUE TITLE
published dictionary arguments do not get through without list arguments

### ISSUE THREAD

**Issue by evanorsouw** [darrenjs/wampcc#15]
When I publish to a topic with the only dictionary data, then the subscriber receives an empty arguments value. When I include just a single list value, all works as expected. E.g.:

`{{}, {{"x",3}}}  ==> {{},{}}`
`{{0},{{"x",3}}}  ==> {{0},{{"x",3}}}`

**Comment by petten** [comment]
Not my experience.

I can receive published messages with a dict alone (i.e., with an empty {} list).

Though I'm using a master version slightly above release 1,3,1.

**Comment by darrenjs** [comment]
Hi,

I'm not able to reproduce this error.   This is what I tried (using latest master):

Started the basic_embedded_router application to have simple router : 

```
basic_embedded_router 44444
```
started a subscriber (using admin tool):
```
admin ws://127.0.0.1:44444 -s TEST  
```
used same admin tool to publish two messages, same as yours:
```
admin ws://127.0.0.1:44444 -p TEST --argdict '{"x":3}'   
admin ws://127.0.0.1:44444 -p TEST --arglist '[0]' --argdict '{"x":3}' 
```
Here's output from the subscriber:
```
topic update: subscription_id: 3, args_list: [], args_dict:{"x": 3}
topic update: subscription_id: 3, args_list: [0], args_dict:{"x": 3}
```
So both messages seem to arrive as expected.  E.g.,  when only the dict is provided (this first line), the subscriber does seem to receive it.

Can you explain more about your test?  E.g., what router did you use?  What subscriber?   Is it possible you could post an example on gist or something?

**Comment by evanorsouw** [comment]
I am at revision 6edd1e34b8f4cf8cea0d880f7bfae5e62265bcde (25 sep) and use version 2.10 of jansson. I am using wampcc both as router and client. I will try to pinpoint the problem in a small program shortly.

**Comment by darrenjs** [comment]
It's worth trying to use latest master, if you are not doing so already.  It's very possible there were some bugs in earlier versions that may the source of the problem you are seeing.
