### ISSUE TITLE
unsubscribe() successful, but the callback unsubscribed_info.was_error is true

### ISSUE THREAD

**Issue by petten** [darrenjs/wampcc#16]
I moved up to release 1.5, although had to change all the callbacks. That came to pass, and all seems well except this:

When calling `unsubscribe()`, the lockable logger I passed to `wampcc` was able to log:

`LOG 20171110-19:22:53.081567 14684  INFO unsubscribed, subscription_id 28, request_id 3 ...`

But upon examining the callback arg `struct unsubscribed_info`, I found its `was_error` member was set to `true`.

I'm sure the previous `wampcc` version that I had used for a long time had its `was_error` member set to the right value, though the `struct` had a different name.

**Comment by darrenjs** [comment]
Yep ... I'm able to reproduce. Seems like bug. Will fix soon.

**Comment by darrenjs** [comment]
fixed on master branch, commit fcb79e5fcf4eae375c08733a395697df124d859f

**Comment by petten** [comment]
Another minor thing - my compiler (`GCC 5.4`) made a little noise about this:

`
... include/wampcc/wamp_session.h:94:28: warning: missing initializer for member 'wampcc::auth_provider::user_secret' [-Wmissing-field-initializers]
           nullptr, nullptr };
`

It can be made to go away by one's adding one more `, nullptr` before `};` at the end.

**Comment by petten** [comment]
Fix confirmed

**Comment by darrenjs** [comment]
added your suggestion to resolve compiler warning.
