### ISSUE TITLE
CMake libuv not found (Windows build)

### ISSUE THREAD

**Issue by KKirillM** [darrenjs/wampcc#17]
`C:\Users\Kirill\Desktop\wampcc\trunk\build>cmake -G "Visual Studio 14 2015" -DLIBUV_DIR=c:/Users/Kirill/Desktop/wam
pcc/trunk/3rdparty/libuv-1.x/ -DJANSSON_DIR=c:/Users/Kirill/Desktop/wampcc/trunk/3rdparty/jansson-master/ -build=c:/User
s/Kirill/Desktop/wampcc/trunk/build c:/Users/Kirill/Desktop/wampcc/trunk/CMakeLists.txt
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using user provided libuv
CMake Error at CMakeLists.txt:95 (message):
  libuv not found
-- Configuring incomplete, errors occurred!`

I download and build libuv and jansson. After that I try to run cmake and have an error. 
Path "c:\Users\Kirill\Desktop\wampcc\trunk\3rdparty\libuv-1.x\" include subfolders "include" (with headers) and "lib" (with libuv.lib file).
CMake version 3.10.

**Comment by darrenjs** [comment]
Is there a space in your  -DLIBUV_DIR   ?
`
-DLIBUV_DIR=c:/Users/Kirill/Desktop/wam pcc/trunk/3rdparty/libuv-1.x/

                                     ^^^^^^
`

**Comment by KKirillM** [comment]
No, there isn't any spaces in this path.

**Comment by darrenjs** [comment]
Have you tried looking in the CMakeError.log , which should be generated when it fails?  It might contain more details on why the libuv wasn't found.  E.g., was it the header, or .lib that couldn't be loaded.
