### ISSUE TITLE
Managing rpc registrations

### ISSUE THREAD

**Issue by codeandroid** [darrenjs/wampcc#21]
**unprovide/unregister**

I've looked for wamp_session::unprovide (or unregister) but it does not exist.
wamp_session::unsubscribe() is available and seems to be similar in spirit.
Do you have plans implementing unprovide()?

**Double registrations**
In case that a session which provides an rpc endpoint crashes or does not shutdown cleanly, the router still holds onto existing registrations and disallows overwriting these dangling registrations.

https://github.com/darrenjs/wampcc/blob/c463d752c1a271dcad8e8252d09fb51227069947/libs/wampcc/rpc_man.cc#L106

What is the intended solution?

In general, it would be great to get a bit more control on the router side to influence the behavior.
For example, a callback used to determine whether a new realm can be opened on-the-fly, or whether a registration can be overwritten.

**Comment by darrenjs** [comment]
Hi,

Yeah, unprovide (or unregister) is missing, that is an oversight.  Will add it to the list of things to do.  

For the rpc_man, the intention was that it should remove procedure registrations for the case of a client that crashes.  When a session is closed, the follow method is invoked to remove any procedures the session had registered : 

https://github.com/darrenjs/wampcc/blob/c463d752c1a271dcad8e8252d09fb51227069947/libs/wampcc/rpc_man.cc#L121

Thanks also for the pull requests ... going through them.

**Comment by codeandroid** [comment]
I missed session_closed - I will test it. Thank you.

**Comment by darrenjs** [comment]
added support for unregister in commit 0012a3ba2e0b9228329ef286b5ad4ade062f51d1
