### ISSUE TITLE
WAMP meta-events

### ISSUE THREAD

**Issue by Livegen77** [darrenjs/wampcc#27]
Hello the WAMP specification define 4 meta-events

> wamp.subscription.on_create
> wamp.subscription.on_subscribe
> wamp.subscription.on_unsubscribe
> wamp.subscription.on_delete

I could'nt find a trace of it in the source code. Are they implemented ? Or did i miss something ? 

Best regards.

**Comment by Livegen77** [comment]
OK  ! Thanks for your feedback !

**Comment by ecorm** [comment]
Is it possible for a custom `auth_provider` to publish such meta events within the handlers?
