### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by jonahzheng** [darrenjs/wampcc#3]
In file included from vendors.cc:8:0:
vendor_jansson.cc:8:21: fatal error: jansson.h: No such file or directory
 #include "jansson.h"
                     ^
compilation terminated.
Makefile:473: recipe for target 'vendors.lo' failed
make[2]: *** [vendors.lo] Error 1
make[2]: Leaving directory '/root/wampcc/jalson/src'
Makefile:404: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/root/wampcc/jalson'
Makefile:405: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by darrenjs** [comment]
Hi

Looks like it cannot find the jansson.h file, which is part lib-jansson.   When you configured the source code, you would have provided an option like `--with-jansson=/opt/jansson-2.7`

Can you check the path you provided for jansson?  Under that path, there should be a file called `include/jansson.h`.   E.g, if the jansson path is `/opt/jansson-2.7` the following file must exist: `/opt/jansson-2.7/include/jansson.h`

**Comment by jonahzheng** [comment]
@darrenjs thank you

/bin/bash ../libtool  --tag=CXX   --mode=link g++ -std=c++11 -Wall -g3 -ggdb -O0 -I/opt/jansson-2.7/include -g -O2 -version-info 0:0:0  -o libwampcc_json.la -rpath /var/tmp/wampcc_install/lib json_pointer.lo jalson.lo vendors.lo /opt/jansson-2.7/lib/libjansson.la 
libtool: link: cannot find the library `/opt/jansson-2.7/lib/libjansson.la' or unhandled argument `/opt/jansson-2.7/lib/libjansson.la'
Makefile:446: recipe for target 'libwampcc_json.la' failed
make[2]: *** [libwampcc_json.la] Error 1
make[2]: Leaving directory '/root/wampcc/jalson/src'
Makefile:404: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/root/wampcc/jalson'
Makefile:405: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by darrenjs** [comment]
Hi

Thanks for this.  So looks like it cannot find `/opt/jansson-2.7/lib/libjansson.la`.  Does that file exist on your machine? Can you try running `ls /opt/jansson-2.7/lib/*` and copy output here ?

**Comment by jonahzheng** [comment]
I build jansson.
$ ./configure
$ make
$ make install

root@debian:/opt/jansson-2.7# ls lib
ls: cannot access lib: No such file or directory
root@debian:/opt/jansson-2.7# ls src
dump.c	 error.lo     hashtable.lo	 hashtable_seed.o     jansson.h		 load.lo    Makefile.am  memory.o	 strbuffer.c   strconv.c   utf.h    value.lo
dump.lo  error.o      hashtable.o	 jansson_config.h     jansson_private.h  load.o     Makefile.in  pack_unpack.c	 strbuffer.h   strconv.lo  utf.lo   value.o
dump.o	 hashtable.c  hashtable_seed.c	 jansson_config.h.in  **libjansson.la**	 lookup3.h  memory.c	 pack_unpack.lo  strbuffer.lo  strconv.o   utf.o
error.c  hashtable.h  hashtable_seed.lo  jansson.def	      load.c		 Makefile   memory.lo	 pack_unpack.o	 strbuffer.o   utf.c	   value.c

**Comment by darrenjs** [comment]
Ok. This is generally not the recommended way to build jansson. What you can try is rebuilding jansson again (starting from a clean directory and fresh unzip) but using the `prefix` option to configure (this tells configure where the final installation is going to live):

    ./configure --prefix=/opt/jansson-2.7

It's also good practise to avoid building from inside the source directory. Buy try this change to configure, followed by `make install`.  If the libs appear, youll know it has worked.

**Comment by jonahzheng** [comment]
ok, thank you. libuv must be build.
https://github.com/libuv/libuv
$ sh autogen.sh
$ ./configure
$ make
$ make check
$ make install

otherwise has error
`wampcc/io_loop.h:20:16: fatal error: uv.h: No such file or directory
 #include <uv.h>
                ^
compilation terminated.
Makefile:570: recipe for target 'ssl_socket.lo' failed
make[1]: *** [ssl_socket.lo] Error 1
make[1]: Leaving directory '/root/wampcc/lib'
Makefile:405: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
`

is this info that the build was successful?
`
root@debian:~/wampcc# make install
............................
libtool: link: g++ -g -O2 -o .libs/test_wamp_rpc test_wamp_rpc.o  -L../lib /root/wampcc/lib/.libs/libwampcc.so -L../jalson/src /root/wampcc/jalson/src/.libs/libwampcc_json.so -L/opt/libuv-1.10.2/lib -luv -lcrypto -lpthread ./.libs/libgtest.a -pthread -Wl,-rpath -Wl,/var/tmp/wampcc_install/lib
make[2]: Entering directory '/root/wampcc/test'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/root/wampcc/test'
make[1]: Leaving directory '/root/wampcc/test'
make[1]: Entering directory '/root/wampcc'
make[2]: Entering directory '/root/wampcc'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/root/wampcc'
make[1]: Leaving directory '/root/wampcc'
`

**Comment by darrenjs** [comment]
Looks like it is still failing, but this time on trying to find the libuv header files.

When you configure libuv, you should use the `--prefix` option, in a similar way to building jansson.  

To test that the wampcc works, try compiling the examples. 

  cd examples
  make

This will likely give errors saying you need to define some environment variables, so define them as required (refer to the paths you have earlier used for libuv, jansson etc).   Also see if the  `admin` program has been installed, under the prefix location you used when configure of wampcc.

**Comment by jonahzheng** [comment]
I don't know what reason.

libtool: link: g++ -g -O2 -o .libs/test_wamp_rpc test_wamp_rpc.o  -L../lib /root/wampcc/lib/.libs/libwampcc.so -L../jalson/src /root/wampcc/jalson/src/.libs/libwampcc_json.so -L/opt/libuv-1.10.2/lib -luv -lcrypto -lpthread ./.libs/libgtest.a -pthread -Wl,-rpath -Wl,/var/tmp/wampcc_install/lib
make[2]: Entering directory '/root/wampcc/test'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/root/wampcc/test'
make[1]: Leaving directory '/root/wampcc/test'
make[1]: Entering directory '/root/wampcc'
make[2]: Entering directory '/root/wampcc'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/root/wampcc'
make[1]: Leaving directory '/root/wampcc'
root@debian:~/wampcc# cd examples/
root@debian:~/wampcc/examples# make
makefile:9: *** WAMPCC_HOME undefined - set WAMPCC_HOME to where wampcc was make-installed.  Stop.

**Comment by darrenjs** [comment]
If in bash, do something like: 

    export WAMPCC_HOME=/root/wampcc

**Comment by jonahzheng** [comment]
ok,thank you.
Recommended as bonefish, add third-party, and auto build.
![Uploading 20170606173943.png…]()

**Comment by darrenjs** [comment]
Hi,  updated the autotools configure.ac etc, so that some of the example programs will get automatically built. So just need to do the normal configure  & make, and some of the examples will be built and then ready to be run.

**Comment by jonahzheng** [comment]
1.
root@debian:/opt# ls -al
total 3692
drwxr-xr-x  6 root root    4096 Jun  8 09:02 .
drwxr-xr-x 22 root root    4096 Apr  3 12:38 ..
drwxrwxr-x  7 test zdz     4096 Oct  2  2014 jansson-2.7
drwxrwxr-x  9 root root    4096 Jan 10 02:42 libuv-1.10.2
drwxr-xr-x 13 root root    4096 Jun  8 09:06 wampcc

2.
export LIBUV_HOME=/opt/libuv-1.10.2
export JANSSON_HOME=/opt/jansson-2.7
export WAMPCC_HOME=/opt/wampcc

cd wampcc/
./fetch_prerequisites.sh

3.
./autotools_setup.sh

4.
./configure  --prefix=/var/tmp/wampcc_install  --with-libuv=/opt/libuv-1.10.2 --with-jansson=/opt/jansson-2.7

5.
make install
////////////////////////////////////////////.
libtool: link: cannot find the library `/opt/jansson-2.7/lib/libjansson.la' or unhandled argument `/opt/jansson-2.7/lib/libjansson.la'
Makefile:447: recipe for target 'libwampcc_json.la' failed
make[2]: *** [libwampcc_json.la] Error 1
make[2]: Leaving directory '/opt/wampcc/jalson/src'
Makefile:404: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/opt/wampcc/jalson'
Makefile:405: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
/////////////////////////////////////////////

**Comment by darrenjs** [comment]
Hi, thanks for this.  I think its worth writing up a step by step guide.

From the above, I can see that those steps have the `configure` command being executed from inside
the wampcc source directory, whereas it only seems to work if executed outside of there.

So, lets say that the intention is to install wampcc under `/opt`  (just like jansson & libuv have been, which is a good pattern).  Then commands can be like:

```shell

# create wampcc base directories
mkdir /opt/wampcc
mkdir /opt/wampcc/build

# clone wampcc into 'src' directory
cd /opt/wampcc
git clone https://github.com/darrenjs/wampcc.git  src

# fetch prerequisities into source directory
cd /opt/wampcc/src
./fetch_prerequisites.sh
./autotools_setup.sh

# configure the make files, from inside the 'build' directory, and set the
# install prefix to be '/opt/wampcc'
cd /opt/wampcc/build
../src/configure --prefix=/opt/wampcc --with-libuv=/opt/libuv-1.10.2 --with-jansson=/opt/jansson-2.7

# compile
make -j

# test that 'basic_embedded_router' was automatically built (only a couple of
# the examples get built automatically)
./examples/basic_embedded_router  55533

# finally, install the wampcc header & libs (into /opt/wampcc)
make install

# check the `admin` command was installed, this will success if the example  
# router is still running
/opt/wampcc/bin/admin 127.0.0.1 55533 -c greeting

# Now try to build all the examples, using the installed header & library
# files. This how custom application would build against wampcc.
export LIBUV_HOME=/opt/libuv-1.10.2
export JANSSON_HOME=/opt/jansson-2.7
export WAMPCC_HOME=/opt/wampcc
cd /opt/wampcc/src/examples
make
```

**Comment by sashakh** [comment]
Hi! Seems to be related to the topic.
With autotools build even when libuv and jansson are installed in standard way, configuration doesn't detect it and complains. Please review and apply if appropriate the patch below. It fixes the issue for me.
[ac.patch.txt](https://github.com/darrenjs/wampcc/files/1543490/ac.patch.txt)

**Comment by sashakh** [comment]
Another issue it is 'makefile' placed in examples - it has higher priority for 'make' program and requires some extra stuff to build normally (which is annoying). With regular automake's Makefile the directory build is fine. I would suggest to rename this 'makefile' for custom uses. Thanks!

**Comment by darrenjs** [comment]
Hi.  For the makefile in 'exampes',   how do you mean it takes higher priority?  During an autotools build, this makefile is skipped over. The intention of this file is to be an example makefile for building the examples, after wampcc has been installed.

**Comment by sashakh** [comment]
Hi @darrenjs !
> For the makefile in 'exampes', how do you mean it takes higher priority?

When 'make' program is invoked it looks for its default makefile in order: makefile, Makefie (https://www.gnu.org/software/make/manual/html_node/Makefile-Names.html)
> During an autotools build, this makefile is skipped over.

Not really, 'makefile' is used first instead of automake's  'Makefile':
```
$ make 
make  all-recursive
make[1]: Entering directory '/home/sashak/src/wampcc'
Making all in libs
make[2]: Entering directory '/home/sashak/src/wampcc/libs'
Making all in json
make[3]: Entering directory '/home/sashak/src/wampcc/libs/json'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/sashak/src/wampcc/libs/json'
Making all in wampcc
make[3]: Entering directory '/home/sashak/src/wampcc/libs/wampcc'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/sashak/src/wampcc/libs/wampcc'
make[3]: Entering directory '/home/sashak/src/wampcc/libs'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/sashak/src/wampcc/libs'
make[2]: Leaving directory '/home/sashak/src/wampcc/libs'
Making all in utils
make[2]: Entering directory '/home/sashak/src/wampcc/utils'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/sashak/src/wampcc/utils'
Making all in tests
make[2]: Entering directory '/home/sashak/src/wampcc/tests'
Making all in json
make[3]: Entering directory '/home/sashak/src/wampcc/tests/json'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/sashak/src/wampcc/tests/json'
Making all in wampcc
make[3]: Entering directory '/home/sashak/src/wampcc/tests/wampcc'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/sashak/src/wampcc/tests/wampcc'
make[3]: Entering directory '/home/sashak/src/wampcc/tests'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/sashak/src/wampcc/tests'
make[2]: Leaving directory '/home/sashak/src/wampcc/tests'
Making all in examples
make[2]: Entering directory '/home/sashak/src/wampcc/examples'
makefile:21: *** WAMPCC_HOME undefined - set WAMPCC_HOME to where wampcc was make-installed.  Stop.
make[2]: Leaving directory '/home/sashak/src/wampcc/examples'
Makefile:426: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/sashak/src/wampcc'
Makefile:358: recipe for target 'all' failed
make: *** [all] Error 2
```
> The intention of this file is to be an example makefile for building the examples, after wampcc has been installed.

That is understood. The problem is that for normal installation 'Makefile' should be used there.

The simple solution would be to rename 'makefile' to something like 'makefile.examples' and after build and installation to create symbolic link:
```
ln -s makefile.examples makefile
```
, and work as you desire.

Another option would be to remove examples/ from SUBDIRS of top level Makefile.am, IOW to exclude it from the build process. But in this case your users will need to bother with 'makefile''s definitions manually.

**Comment by darrenjs** [comment]
Hi, okay, I see this happens when configure has been executed inside the source tree.  I renamed the makefile.  And incorparated your patch also.  Many thanks for the feedback.

**Comment by sashakh** [comment]
Thank you for the great project and quick response. )

**Comment by jonahzheng** [comment]
`root@ubuntu:/opt/wampcc/build$ sudo ../src/configure --prefix=/opt/wampcc --with-libuv=/opt/libuv-1.10.2 --with-jansson=/opt/jansson-2.7
root@ubuntu:/opt/wampcc/build$ make install
Making install in libs
make[1]: Entering directory '/opt/wampcc/build/libs'
Making install in json
make[2]: Entering directory '/opt/wampcc/build/libs/json'
depbase=`echo vendors.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../../src/libs/json -I../..    -I../../../src/include -I../../../src/3rdparty/msgpack-c/include -I/opt/jansson-2.7/include -std=c++11 -Wall -g -O2 -MT vendors.lo -MD -MP -MF $depbase.Tpo -c -o vendors.lo ../../../src/libs/json/vendors.cc &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../../src/libs/json -I../.. -I../../../src/include -I../../../src/3rdparty/msgpack-c/include -I/opt/jansson-2.7/include -std=c++11 -Wall -g -O2 -MT vendors.lo -MD -MP -MF .deps/vendors.Tpo -c ../../../src/libs/json/vendors.cc  -fPIC -DPIC -o .libs/vendors.o
In file included from ../../../src/libs/json/vendors.cc:8:0:
../../../src/libs/json/vendor_jansson.h:10:66: fatal error: jansson.h: No such file or directory
compilation terminated.
Makefile:492: recipe for target 'vendors.lo' failed
make[2]: *** [vendors.lo] Error 1
make[2]: Leaving directory '/opt/wampcc/build/libs/json'
Makefile:374: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/opt/wampcc/build/libs'
Makefile:426: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
`

**Comment by darrenjs** [comment]
So it cannot find `jansson.h`.      It  looks like you have installed jansson under `/opt/jansson-2.7`  .   The header file should thus be at:   `/opt/jansson-2.7/include/jansson.h`   ... if you have installed jansson using the standard configure approach.    It's either not there, or, the `root` user does not have permission to access it; I note that the `jansson-2.7` folder is owned by a different user  `fxkjroot` .... that's possibly the reason.   

Note that it's not generally recommended to do build/test/install as root etc.
