### ISSUE TITLE
Remove pkg-config from CMakeLists.txt

### ISSUE THREAD

**Issue by JulZimmermann** [darrenjs/wampcc#30]
Since 917c809438cb52e46191666d41c5e1ee9709b15a CMakeLists.txt uses pkg-config. This breaks platform independence because pkg-config isn't available for windows systems.

Please remove pkg-config from CMakeLists.txt

**Comment by JulZimmermann** [comment]
OK, i just realized by adding -DJANSSON_DIR and -DLIBUV_DIR pkg-config isn't used at all.

More build documentation for windows would be nice :)

**Comment by darrenjs** [comment]
Will leave this issue as open; more documentation needed for windows build
