### ISSUE TITLE
tcp_nodelay option

### ISSUE THREAD

**Issue by BenKaufmann** [darrenjs/wampcc#34]
Hi,

we noticed some pretty bad performance when doing a simple pub-sub ping-pong over local network. After some digging around, we found the problem to be a missing `tcp_nodelay` option on the tcp socket.
Unfortunately, it looks like wampcc does not support setting options on its tcp socket. 

Do you plan to add such an API? Further, is there a particular reason why `tcp_nodelay` is not enabled by default?

**Comment by darrenjs** [comment]
Hi,  no particular reason for it not being there.  But agree, definitely should be added, and soon.   I am considering couple approaches: return the raw file-handle (for user to then set); return the libuv file object (again for user to then set); or provide method named like `set_tcp_nodelay()`.

**Comment by BenKaufmann** [comment]
Hi,
the option seems to be particular important on the router, so I think it should also be added to the router's listen options. Maybe one could introduce some kind of `socket_option` struct that could then be used both in the router's `listen_options` and in some constructor of `tcp_socket`.

**Comment by darrenjs** [comment]
added in commit 11997249dec5829e6aebbf532789b3bbbacb10a3

**Comment by BenKaufmann** [comment]
Thanks a lot.
