### ISSUE TITLE
Q: Kernel configured with ssl=true usable with tcp_socket / session, too?

### ISSUE THREAD

**Issue by petten** [darrenjs/wampcc#37]
So far I've used multiple tcp_sockets and multiple wamp_sessions with a single non-ssl kernel.

To be able to use an ssl_socket, naturally one has to pass config.ssl = true to the kernel ctor.

Q: Does this ssl=true kernel still work with tcp_sockets? In other words, can a single ssl=true kernel be used simultaneously by multiple tcp_sockets and ssl_sockets? Or is it advisable to make two separate kernels for use with tcp_sockets and ssl_sockets, respectively?

**Comment by darrenjs** [comment]
Yes, a wampcc::kernel configured to support ssl can also be used by plain tcp sockets.   You could make separate kernels, but you just end up creating more threads than you really need.   Note that in addition to  setting the boolean `enable` to true,  you also need to provide the certificate and key files, if you are creating a router project.

**Comment by petten** [comment]
All right, I'll use just one ssl_socket kernel. (My current project includes caller and callee, none acting as a router.)

Thanks!
