### ISSUE TITLE
How does multi-threading work in wampcc router?

### ISSUE THREAD

**Issue by Mdrbhatti** [darrenjs/wampcc#48]
Hi Darren,

From what I could tell traversing thru the source code of the wampcc router(correct me if I am wrong), there is a main event loop which handles all the incoming connections, and for each client a separate session/thread, is created.

I am trying to benchmark the multi-core performance of the wampcc router by using various scenarios. E.g. Multiple publishers pushing at different rates, multiple subscribers subscribing etc...

I have 3 raspberry pi's (Model B, Debian linux) running only one of the following:
1) Multiple Autobahn|Python clients (subscribing to some topics)
2) Multiple Autobahn|Python clients (publishing to some topics)
3) wampcc router

So far, I have noticed that the wampcc router doesn't seem to be using more than 2 cores (the raspberry pi is quadcore).

Therefore, I wanted to ask whether the router spawns any new threads (from a wamp session), to handle the increasing load. E.g. if I increase the rate of publishes per second, will a new thread be spawned by the router to handle the increasing load. Additionally, will something similar happen when there are a lot of subscribers,

Under what scenarios will new threads be spawned by the router? Any help would be appreciated!

Thanks!

**Comment by darrenjs** [comment]
Hi,

wampcc internally will use only two threads.   One thread is used for network input/output (in source code comments, this is typically labelled "IO").  So calls to connect, listen, read/write are done on IO.   Then a second thread is used for message dispatch from the wampcc library into application code; this is the event handler thread (typically labelled "EV" in code comments).  So no matter how many sessions an application has,  it will have 2 threads per wampcc::kernel object (and typically you only have a single kernel instance).   These two threads are created when kernel is constructed; it doesn't depend on waiting for wamp sessions to be created (I think they get logged, too).

**Comment by Mdrbhatti** [comment]
Ah, that explains it. Thanks!
