### ISSUE TITLE
error while make -f examples.makefile

### ISSUE THREAD

**Issue by infrontofme** [darrenjs/wampcc#61]
Hi, when I do ` make -f examples.makefile `, an error occurred, I can't handle it.
`
/usr/bin/ld: /opt/libuv/lib/libuv.a(libuv_la-fs.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'wamp_router/router' failed
make: *** [wamp_router/router] Error 1
`
it seems something wrong with libuv, I do build wampcc on Linux as README.MD do.
could you help me with this problem ? That will thank you very much.

OS: Ubuntu16.04

thanks :)

**Comment by darrenjs** [comment]
well from that message, it appears that the `libdl` is missing from the link line; you could try modifying the examples.makefile, to add `-ldl` to the `LDLIBS` variable.   I must admit I have not tried to compile on Ubuntu 16.  what version of GCC did you use?
