### ISSUE TITLE
How to send binary data ?

### ISSUE THREAD

**Issue by Green7** [darrenjs/wampcc#7]
MsgPack support binary data. How to send it in wampcc?

**Comment by darrenjs** [comment]
Hi, I think you could use [base64](https://stackoverflow.com/questions/1443158/binary-data-in-json-string-something-better-than-base64) encoding.  So convert your data into base64 string, and then send it as a string.

**Comment by Green7** [comment]
:( base64 is not an option in my case. 
I need good performance beacuse I send a lot of data. Conversion to base64 will increase amount of data by 33% ...

**Comment by darrenjs** [comment]
Yeah, base64 does have that size & cpu overhead.  But the problem with trying to support binary directly is that it is not part of the JSON specification, so there is going to be undefined behaviour in various scenarios.  E.g. what if you have a WAMP callee that replies in msgpack containing binary, but the original caller is using plain JSON?  A WAMP router would have to make a decision: does it drop the reply, or send an error to the caller, or something else?

But I think it could be added.   The `json_value` class could be changed to allow a new sub-type, (eg, `json_binary` or something), and that would only be supported by msgpack (and later cbor); an exception would be thrown if a plain json serialiser was used with such messages.   I don't think it is much work to add this, but right now I'm in the middle of a refactor, cleaning up the naming of public api.

**Comment by Green7** [comment]
I think that is not a problem. Router should handle this kind of request. Calle should know what he does and what kind of data expect. Or when calle uses json router can convert data to base64 ....
